//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8762.
// 
namespace KoctasWM_Project.WS_Yardim {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZKT_WM_WS_YARDIM", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZKT_WM_WS_YARDIMService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ZKT_WM_WS_YARDIMService() {
            this.Url = "http://kterpdev.koctas.com.tr:8000/sap/bc/srt/rfc/sap/zkt_wm_ws_yardim/500/zkt_wm" +
                "_ws_yardimservice/zkt_wm_ws_yardim";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZKT_WM_WS_YARDIM:ZKtWmWsKargoFir" +
            "malariRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZKtWmWsKargoFirmalariResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZKtWmWsKargoFirmalariResponse ZKtWmWsKargoFirmalari([System.Xml.Serialization.XmlElementAttribute("ZKtWmWsKargoFirmalari", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZKtWmWsKargoFirmalari ZKtWmWsKargoFirmalari1) {
            object[] results = this.Invoke("ZKtWmWsKargoFirmalari", new object[] {
                        ZKtWmWsKargoFirmalari1});
            return ((ZKtWmWsKargoFirmalariResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginZKtWmWsKargoFirmalari(ZKtWmWsKargoFirmalari ZKtWmWsKargoFirmalari1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ZKtWmWsKargoFirmalari", new object[] {
                        ZKtWmWsKargoFirmalari1}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZKtWmWsKargoFirmalariResponse EndZKtWmWsKargoFirmalari(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZKtWmWsKargoFirmalariResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZKT_WM_WS_YARDIM:ZKtWmWsSayimKyt" +
            "OnceKontRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZKtWmWsSayimKytOnceKontResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZKtWmWsSayimKytOnceKontResponse ZKtWmWsSayimKytOnceKont([System.Xml.Serialization.XmlElementAttribute("ZKtWmWsSayimKytOnceKont", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZKtWmWsSayimKytOnceKont ZKtWmWsSayimKytOnceKont1) {
            object[] results = this.Invoke("ZKtWmWsSayimKytOnceKont", new object[] {
                        ZKtWmWsSayimKytOnceKont1});
            return ((ZKtWmWsSayimKytOnceKontResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginZKtWmWsSayimKytOnceKont(ZKtWmWsSayimKytOnceKont ZKtWmWsSayimKytOnceKont1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ZKtWmWsSayimKytOnceKont", new object[] {
                        ZKtWmWsSayimKytOnceKont1}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZKtWmWsSayimKytOnceKontResponse EndZKtWmWsSayimKytOnceKont(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZKtWmWsSayimKytOnceKontResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZKT_WM_WS_YARDIM:ZKtWmWsKoliTipl" +
            "eriRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZKtWmWsKoliTipleriResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZKtWmWsKoliTipleriResponse ZKtWmWsKoliTipleri([System.Xml.Serialization.XmlElementAttribute("ZKtWmWsKoliTipleri", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZKtWmWsKoliTipleri ZKtWmWsKoliTipleri1) {
            object[] results = this.Invoke("ZKtWmWsKoliTipleri", new object[] {
                        ZKtWmWsKoliTipleri1});
            return ((ZKtWmWsKoliTipleriResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginZKtWmWsKoliTipleri(ZKtWmWsKoliTipleri ZKtWmWsKoliTipleri1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ZKtWmWsKoliTipleri", new object[] {
                        ZKtWmWsKoliTipleri1}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZKtWmWsKoliTipleriResponse EndZKtWmWsKoliTipleri(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZKtWmWsKoliTipleriResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZKtWmWsKargoFirmalari {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktWmKoliTipi {
        
        private string mandtField;
        
        private string koliTipiField;
        
        private string tanimField;
        
        private decimal desiField;
        
        private string meinsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KoliTipi {
            get {
                return this.koliTipiField;
            }
            set {
                this.koliTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tanim {
            get {
                return this.tanimField;
            }
            set {
                this.tanimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Desi {
            get {
                return this.desiField;
            }
            set {
                this.desiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Meins {
            get {
                return this.meinsField;
            }
            set {
                this.meinsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktWmSayimCnl {
        
        private string mandtField;
        
        private string lgnumField;
        
        private string lgplaField;
        
        private string lenumField;
        
        private string matnrField;
        
        private string ean11Field;
        
        private decimal mengeField;
        
        private string meinsField;
        
        private string lgtypField;
        
        private string unameField;
        
        private string udateField;
        
        private string uzeitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lgnum {
            get {
                return this.lgnumField;
            }
            set {
                this.lgnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lgpla {
            get {
                return this.lgplaField;
            }
            set {
                this.lgplaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lenum {
            get {
                return this.lenumField;
            }
            set {
                this.lenumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ean11 {
            get {
                return this.ean11Field;
            }
            set {
                this.ean11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Menge {
            get {
                return this.mengeField;
            }
            set {
                this.mengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Meins {
            get {
                return this.meinsField;
            }
            set {
                this.meinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lgtyp {
            get {
                return this.lgtypField;
            }
            set {
                this.lgtypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Uname {
            get {
                return this.unameField;
            }
            set {
                this.unameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Udate {
            get {
                return this.udateField;
            }
            set {
                this.udateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Uzeit {
            get {
                return this.uzeitField;
            }
            set {
                this.uzeitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktWmVwKrfirm {
        
        private string mandtField;
        
        private string lifnrField;
        
        private string serviceField;
        
        private string serviceTypeField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string name1Field;
        
        private string name2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lifnr {
            get {
                return this.lifnrField;
            }
            set {
                this.lifnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktWmReturn {
        
        private string msgtyField;
        
        private string msgidField;
        
        private string msgnoField;
        
        private string messageField;
        
        private string msgv1Field;
        
        private string msgv2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msgty {
            get {
                return this.msgtyField;
            }
            set {
                this.msgtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msgid {
            get {
                return this.msgidField;
            }
            set {
                this.msgidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msgno {
            get {
                return this.msgnoField;
            }
            set {
                this.msgnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msgv1 {
            get {
                return this.msgv1Field;
            }
            set {
                this.msgv1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msgv2 {
            get {
                return this.msgv2Field;
            }
            set {
                this.msgv2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZKtWmWsKargoFirmalariResponse {
        
        private ZktWmReturn[] esResponseField;
        
        private ZktWmVwKrfirm[] etKargoFirmasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktWmReturn[] EsResponse {
            get {
                return this.esResponseField;
            }
            set {
                this.esResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktWmVwKrfirm[] EtKargoFirmasi {
            get {
                return this.etKargoFirmasiField;
            }
            set {
                this.etKargoFirmasiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZKtWmWsSayimKytOnceKont {
        
        private string ivLgplaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IvLgpla {
            get {
                return this.ivLgplaField;
            }
            set {
                this.ivLgplaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZKtWmWsSayimKytOnceKontResponse {
        
        private ZktWmReturn[] esResponseField;
        
        private ZktWmSayimCnl[] etCnliSymField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktWmReturn[] EsResponse {
            get {
                return this.esResponseField;
            }
            set {
                this.esResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktWmSayimCnl[] EtCnliSym {
            get {
                return this.etCnliSymField;
            }
            set {
                this.etCnliSymField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZKtWmWsKoliTipleri {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZKtWmWsKoliTipleriResponse {
        
        private ZktWmReturn[] esResponseField;
        
        private ZktWmKoliTipi[] etKoliTipiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktWmReturn[] EsResponse {
            get {
                return this.esResponseField;
            }
            set {
                this.esResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZktWmKoliTipi[] EtKoliTipi {
            get {
                return this.etKoliTipiField;
            }
            set {
                this.etKoliTipiField = value;
            }
        }
    }
}
